config/routes.rb
Rails.application.routes.draw do

  resource :game do
    collection do
      patch :reveal
      post :reset
    end
  end

  root 'games#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board

  attr_reader :rows, :columns, :tiles, :mines_count, :moves_count, :lost

  def initialize(rows, columns, mines_count)
    @rows, @columns, @mines_count = rows, columns, mines_count
    reset!
  end

  def reset!
    @lost = false
    @moves_count = 0
    initialize_tiles
    populate_mines
  end

  def reveal(row, column)
    return if lost
    @moves_count = @moves_count + 1
    get_tile(row, column).tap do |tile|
      @lost = true if tile.mine
      tile.reveal!
    end
  end

  def get_tile(row, column)
    @tiles[column][row]
  end

private

  def initialize_tiles
    @tiles = Array.new(@columns) { |column| Array.new(@rows) { |row| Tile.new(row, column, self) } }
  end

  def populate_mines
    @mines_count.times do |i|
      get_tile(rand(@columns), rand(@rows)).mine = true
    end
  end

end

app/models/tile.rb
class Tile

  attr_reader :row, :column, :revealed
  attr_accessor :mine

  def initialize(row, column, board)
    @row, @column, @board = row, column, board
    @revealed = @mine = false
    @neighbor_mines = 0
  end

  def reveal!
    @revealed = true
  end

  def get_neighbors
    @board.tiles.flatten.select do |t|
      (t.row <= row + 1 && t.row >= row - 1) &&
      (t.column <= column + 1 && t.column >= column - 1) &&
      t != self
    end
  end

  def neighbor_mines_count
    get_neighbors.select { |t| t.mine }.size
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :board

  ROWS_COUNT = COLUMNS_COUNT = 10
  MINES = 10

  def board
    $board ||= Board.new(ROWS_COUNT, COLUMNS_COUNT, MINES)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index

  end

  def reveal
    board.reveal(params[:row].to_i, params[:column].to_i)
    redirect_to action: :index
  end

  def reset
    board.reset!
    redirect_to action: :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/index.html.haml
%h1 Minesweeper
-if board.lost
  .alert.alert-danger
    <b>You lost!</b> Click the button below to start a new game.
%table#board.table-bordered
  -board.columns.times do |column|
    %tr
      -board.rows.times do |row|
        -board.get_tile(row, column).tap do |tile|
          %td
            -if !tile.revealed
              =link_to '', reveal_game_path(row: row, column: column), method: :patch
            -else
              .revealed
                -if tile.mine
                  .mine M!
                -else
                  =tile.neighbor_mines_count > 0 ? tile.neighbor_mines_count : ''


%p <b>#{board.moves_count}</b> moves
%p=link_to 'Reset', reset_game_path, method: :post, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to reset the current game?' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Minesweeper!
    =stylesheet_link_tag 'application'
    =javascript_include_tag 'application'
    =csrf_meta_tags

%body
  .container
    =yield